@Backend_HostAddress = https://localhost:5001


POST {{Backend_HostAddress}}/api/WasteReports/
Content-Type: application/json

{
    "id": 13,
    "wasteType": "Plastic",
    "wasteAmount": 20,
    "wasteProcessingFacility": "Recycling",
    "wasteCollector": "string"
}

###

GET {{Backend_HostAddress}}/api/WasteReports/

###

GET {{Backend_HostAddress}}/api/WasteReports/8

###

GET {{Backend_HostAddress}}/api/WasteReports/?type=Plastic

###

POST {{Backend_HostAddress}}/api/People
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "employeeId": "123459",
    "password": "password123",
    "role": "Manager"
}

###

GET {{Backend_HostAddress}}/api/People

###

GET {{Backend_HostAddress}}/api/People/?role=Employee

###

GET {{Backend_HostAddress}}/api/People/?active=true

###

GET {{Backend_HostAddress}}/api/People/?role=Employee&active=true

###

PUT {{Backend_HostAddress}}/api/People/123456
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "password",
    "role": "Employee"
}

###

